a=input('Digite algo:')
print(a,'Pertence a qual classe?')
print(type(a))
print('')
print(a,'É um número?')
print(a.isnumeric())
print('')
print(a,'É um número decimal?')
print(a.isdecimal())
print('')
print(a,'É uma letra?')
print(a.isalpha())
print('')
print(a,'É uma letra ou número?')
print(a.isalnum())
print('')
print(a,'Está somente com letra(s) maiúscula(s)?')
print(a.isupper())
print('')
print(a,'Está somente com letra(s) minúscula(s)?')
print(a.islower())
print('')
print(a,'É um dígito?')
print(a.isdigit())
print('')
print(a,'É um espaço?')
print(a.isspace())
print('')
print(a, 'É um identificador?')
print(a.isidentifier())
print('')

