print('DESAFIO 27')
print('')
nome=str(input('Digite seu nome completo:')).strip().title()
n=nome.split()
print('Muito prazer!!!')
print('Seu primeiro nome é {}'.format(n[0]))
print('Seu último nome é {}'.format(n[len(n)-1]))