print(' ')
print('VAMOS CALCULAR COMIGO?')
print(' ')
x=int(input('Digite um número '))
y=int(input('Digite outro número '))
somar=(x+y)
subtrair=(x-y)
multiplicar=(x*y)
dividir=(x/y)

print('A soma desses números é:',somar)
print('A subtração desses números é:',subtrair)
print('A multiplicação é:',multiplicar)
print('A divisão é:',dividir)
print(' ')
print('Vamos além...')
