frase=('Curso em Vídeo Python')
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[13:])
print(frase[1:13])
print(frase.count('o'))
print(len(frase))
print(frase.replace('Python','Android'))
print('Curso'in frase)
print(frase.find('Vídeo'))
print(frase.lower())
print(frase.lower().find('vídeo'))
print(frase.upper())
print(frase.split())
dividido=frase.split()
print(dividido[2])
print(dividido[2][3])